import Problems from "@/partials/Problems";
import Services from "@/partials/Services";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Our services',
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="py-30">
      <Services count={12} exploreBlock={false} />
      <Problems />
    </div>
  )
}