import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'About us',
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="">
      About
    </div>
  )
}