import { Metadata } from "next";
import Image from "next/image";
import slideImg1 from '../../public/section-img-3.png';
import { teamCardItems } from "@/data";
import { Facebook, Instagram, Youtube } from "lucide-react";
import { ourFoundationCardItems } from "@/data";
import Testimonials from "@/partials/Tesimonials";
import * as motion from "motion/react-client"
import { containerStagger, fadeIn, fadeInUp } from "@/motion/animation";

export const metadata: Metadata = {
  title: 'About us',
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <motion.section className="pt-30"
        initial={'hidden'}
        whileInView={'visible'}
        variants={containerStagger}
        viewport={{ once: false }}
      >
        <div className="container">
          <div className="text-center">
            <motion.p variants={fadeInUp} className="section-desc">About us</motion.p>
            <motion.p variants={fadeInUp} className="section-title">Delivering reliable solutions for over 15 years </motion.p>
            <motion.p variants={fadeInUp}>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aperiam, eius maiores vero dolorem aliquid incidunt reiciendis necessitatibus quis, adipisci laborum laboriosam fugit reprehenderit consequatur! Porro eaque dolor consequatur doloremque expedita.</motion.p>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-20 items-center mt-20">
            <div>
              <motion.div variants={fadeInUp} className="section-desc mb-5">Our story</motion.div>
              <motion.h3 variants={fadeInUp} className="section-title mb-5">From humble beginnings to trusted experts</motion.h3>
              <motion.p variants={fadeInUp}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex eveniet, aspernatur harum ab molestiae corrupti rerum consectetur sed id facere magnam, nam magni ipsa quasi praesentium aperiam? Libero odit officia voluptatibus atque dicta est repellendus sequi doloribus? Repudiandae repellendus odio officia culpa, sint eius, natus, animi a ut impedit dolore porro? Laboriosam pariatur temporibus tempore veritatis ea, similique excepturi est. Repudiandae sunt labore voluptas excepturi harum nesciunt in molestiae dignissimos eaque provident, doloribus nostrum! Accusantium adipisci temporibus eligendi facilis sapiente cumque, ut harum dolor error, voluptatum quaerat pariatur earum, corporis vel! Quia, adipisci. Eaque, veniam. Aspernatur voluptatum laudantium debitis quo.</motion.p>
            </div>
            <div className="flex justify-end">
              <motion.div variants={fadeIn} className="">
                <Image src={slideImg1} alt="" width={500} height={500} className="rounded-2xl" />
              </motion.div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 my-20">
            {teamCardItems.map(item => {
              return (
                <motion.div variants={fadeInUp} className="relative bg-gray-200 rounded-2xl">
                  <Image src={item.img} width={300} height={100} alt="" />
                  <div className="absolute bottom-0 left-0 p-3 w-full">
                    <div className="relative bg-secondary p-3 text-center rounded-lg min-h-30">
                      <ul className="absolute -top-4 left-0 w-full group">
                        <button className="bg-primary size-10 rounded-full text-white cursor-pointer">+</button>
                        <ul className="absolute -top-[120%] left-[50%] -translate-x-[50%] bg-white hidden group-hover:flex gap-x-5 rounded-full p-3">
                          <li><Instagram /></li>
                          <li><Facebook /></li>
                          <li><Youtube /></li>
                        </ul>
                      </ul>
                      <div className="font-bold mt-4">{item.name}</div>
                      <div className="">{item.role}</div>
                    </div>
                  </div>
                </motion.div>
              )
            })}
          </div>
          <div className="text-center mb-15">
            <motion.div variants={fadeInUp} className="section-desc">Our fundations</motion.div>
            <motion.h3  variants={fadeInUp}className="section-title">The principles behind <br /> our success</motion.h3>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 mb-20">
            {ourFoundationCardItems.map(item => {
              const Icon = item.icon
              return (
                <motion.div variants={fadeInUp} className="text-center flex flex-col items-center gap-5">
                  <div className="bg-secondary size-20 rounded-full flex items-center justify-center">
                    <Icon size={32} color="#092c52" />
                  </div>
                  <p className="font-bold">{item.title}</p>
                  <p>{item.text}</p>
                </motion.div>
              )
            })}
          </div>
        </div>

      </motion.section>

    </>
  )
}