import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ChevronUp } from "lucide-react";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'Plumber site | Expert Plumbing services provider',
    template: '%s | Plumber site - Expert Plumbing services provider'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
      <a href="#" className="fixed p-2 right-5 bottom-5 bg-secondary rounded-full z-99"><ChevronUp color="black" /></a>
    </html>
  );
}
